import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
  screen: {
    padding: 20,
    backgroundColor: "#222",
    height: "100%",
  },
  container: {
    flex: 1,
  },
  input: {
    height: 60,
    paddingLeft: 30,
    paddingRight: 30,
    marginBottom: 20,
    borderWidth: 0,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 10,
    fontSize: 18,
    color: "#ffffff",
  },
  button: {
    height: 45,
    width: "100%",
    backgroundColor: "white",
    borderRadius: 10,
    alignSelf: "center",
    padding: 10,
    marginTop: 20,
  },
  header: {
    fontSize: 30,
    color: "white",
    fontWeight: "bold",
  },
  bookingHeader: {
    fontSize: 35,
    color: "white",
  },
  title: {
    color: "gray",
    marginVertical: 10,
  },
  centeredView: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    width: "100%",
    height: "90%",
    backgroundColor: "#222",
    padding: 10,
    alignItems: "center",
    shadowColor: "#111",
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 5,
    borderRadius: 10,
  },
  inputS: {
    height: 40,
    width: "90%",
    paddingLeft: 20,
    paddingRight: 20,
    marginBottom: 20,
    marginTop: 20,
    borderWidth: 0,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 10,
    fontSize: 18,
    color: "#ffffff",
  },
  listItem: {
    padding: 15,
    borderRadius: 5,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    marginVertical: 5,
  },
});
